### ISSUE TITLE
like uuid used using type uuid string to send to hasura what to do for bigint

### ISSUE THREAD

**Issue by bete7512** [hasura/go-graphql-client#110]
variable 'userId' is declared as 'Int', but used where 'bigint' is expected, Locations: [], Extensions: map[code:validation-failed path:$.selectionSet.insertUsersUserRolesOne.args.object.userId]
I tried this 	
1,
```
type bitgint int
variables := map[string]interface{}{
		"userId": bigint(newUser.InsertUsersUsersOne.Id),
		"role":   "USER",
	}
```
2,also I tried
`HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES=true
`
then I sent userId as a string but still doesnot work

thanks

**Comment by bete7512** [comment]
I tried this 	
1,type bigint int
	variables := map[string]interface{}{
		"userId": bigint(newUser.InsertUsersUsersOne.Id),
		"role":   "USER",
	}
2,also I tried #HASURA_GRAPHQL_STRINGIFY_NUMERIC_TYPES=true
then I sent userId as a string but still doesnot work

**Comment by hgiasac** [comment]
Hmm, your code should work. Anyway, you can define a reusable type instead. 

```go
type BigInt int 

func (bi BigInt) GetGraphQLType() string { 
  return "bigint" 
}
```

or use the `ConstructQuery` function to print the GraphQL string output for debugging
