### ISSUE TITLE
field 'update_schema_event' not found in type: 'query_root',

### ISSUE THREAD

**Issue by MohamedKHALILRouissi** [hasura/go-graphql-client#115]
am doing this query and am always getting 
error Message: field 'update_schema_event' not found in type: 'query_root', Locations: [], Extensions: map[code:validation-failed path:$.selectionSet.update_schema_event]
when i do it in hasura console it works 

code 
```
func UpdateSchemaResult(id int, result string) error {
	client := startgraphqlconnection()

	var mutation struct {
		update_schema_event struct {
			Affected_Rows int `json:"affected_rows"`
		} `graphql:"update_schema_event(where: { id: { _eq: $id }}, _set: { result_id: $result })"`
	}
	variables := map[string]interface{}{
		"id":     id,
		"result": result,
	}

	err := client.Query(context.Background(), &mutation, variables)
	if err != nil {
		fmt.Println("error", err)
		return err
	}
	return nil
}
```

i also tried with this method but the same result 

```
	var mutation struct {
		Updateschemaevent struct {
			AffectedRows int `graphql:"affected_rows"`
		} `graphql:"update_schema_event(where: $where, _set: $set)"`
	}
	variables := map[string]interface{}{
		"where": schema_event_bool_exp{
			"id": map[string]interface{}{
				"_eq": id,
			},
		},
		"set": schema_event_set_input{
			"result_id": result,
		},
	}
```
thanks for help

**Comment by MohamedKHALILRouissi** [comment]
![image](https://github.com/hasura/go-graphql-client/assets/124497891/f192515c-fbad-453a-afc4-21add51216cb)

**Comment by hgiasac** [comment]
The console uses an admin secret with full access to the GraphQL schema. You should check if the client also set `x-hasura-admin-secret`  or Authorization header if the client uses JWT/custom auth

**Comment by MohamedKHALILRouissi** [comment]
i already defined that , i have another query that works fine , and am using the root user have all permissions
