### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by steeling** [hasura/go-graphql-client#117]
https://github.com/nhooyr/websocket explicitly has several (indirect) vulnerabilities at the current version. By upgrading to the latest version, which has no third party dependencies, we'd be able to pass our vuln scans

**Comment by steeling** [comment]
better yet would be to switch to https://pkg.go.dev/golang.org/x/net/websocket

**Comment by hgiasac** [comment]
Upgrade dependencies on [v0.10.2](https://github.com/hasura/go-graphql-client/releases/tag/v0.10.2)
The `net/websocket` client is deprecated. Switching to that library isn't the right choice. Its documentation also recommends nhooyr or gorilla websocket
