### ISSUE TITLE
Can't get graphql-ws protocol working

### ISSUE THREAD

**Issue by chuongle** [hasura/go-graphql-client#125]
Here is the current code that I have

```go
subscriptionClient = graphql.NewSubscriptionClient("ws://localhost:8888/graphql").
	WithConnectionParams(map[string]interface{}{
		"headers": map[string]string{
			"Authorization": "Bearer " + token,
		},
	}).
	WithProtocol(graphql.GraphQLWS).
	OnConnected(func() {
		log.Println("Connected")
	}).
	OnDisconnected(func() {
		log.Println("Disconnected")
	}).
	OnError(func(sc *graphql.SubscriptionClient, err error) error {
		log.Println(err.Error())
		return err
	})

_, err := subscriptionClient.Subscribe(query, nil, func(data []byte, errValue error) error {
	if errValue != nil {
		// handle error
		// if returns error, it will failback to `onError` even
		return errValue
	}

	// handle data here

	return nil
})

if err != nil {
	log.Fatal("Error when subscribe: ", err)
}

err = subscriptionClient.Run()

if err != nil {
	log.Fatal("Error Starting Subscription: ", err)
} else {
	log.Println("No error here")
	os.Exit(1)
}
```

When I tried to run this code, I got the error `failed to read JSON message: failed to get reader: received close frame: status = StatusCode(4403) and reason = "Forbidden"`. But if I switched to the subscription transport protocol, it's working normally. I can assure the server side (not Hasura) is working because I have a NodeJS application subscribe to the server using graphql-ws protocol. Can someone give me some clue where I can try to debug this?

**Comment by hgiasac** [comment]
You should check your server logs for more context. The 4403 status code means the client has failed to authorize the credential. Or the connection parameters are in a different structure.

```go
// different format per different server specs
{
	"headers": map[string]string{
		"Authorization": "Bearer " + token,
	},
}
```

We can't reproduce it unless you can share the framework name ([graphql-ws](https://the-guild.dev/graphql/ws/get-started#start-the-server), apollo,...) or service of the GraphQL server. Do you implement the graphql server with

**Comment by chuongle** [comment]
@hgiasac to be specific, we are using this [recipe](https://the-guild.dev/graphql/ws/recipes#ws-server-usage-with-subscriptions-transport-ws-backwards-compatibility) because we want to support both graphql-ws and subscription-transport-ws.

I will try to debug some more on the server side

**Comment by hgiasac** [comment]
@chuongle you should find the code line with `close(4403, 'Forbidden')` the on server code. Because the custom auth is implemented by your team. The exit code is emitted manually.

In this [auth recipe](https://the-guild.dev/graphql/ws/recipes#server-usage-with-ws-and-custom-auth-handling), if the server authorizes on `onConnect` or `onSubscribe` events, it will return the status code `4500`. The status code `4403` is emitted after upgrading the WebSocket connection.

**Comment by chuongle** [comment]
@hgiasac Sorry for the delay. thank you for some of the hints. I was able to identify the issue. I will close this now.
