### ISSUE TITLE
Get list/map of subscriptions

### ISSUE THREAD

**Issue by andrexus** [hasura/go-graphql-client#131]
I'm currently utilizing the **GetSubscription(id string)** method in the subscription client, which allows to retrieve a subscription by its ID. However, I'd like to propose a new feature that could enhance the functionality of the subscription client.

Could your consider adding a new method that returns a list or map of all subscriptions that have been registered by a client?

Use case:
The motivation behind this request is to improve error handling. When an error occurs, the **OnError** callback is triggered. I want to engage all subscription handlers and pass along the error. As it stands, I need to manually track all subscriptions because the subscription client doesn't reveal the underlying subscriptions map. 

This proposed feature could streamline the process and enhance the efficiency of error handling.

**Comment by hgiasac** [comment]
Make sense. I have exposed the method https://github.com/hasura/go-graphql-client/pull/132

**Comment by andrexus** [comment]
Many many thanks!!!
