### ISSUE TITLE
Better library error returns

### ISSUE THREAD

**Issue by emilaleksanteri** [hasura/go-graphql-client#135]
Would it be possible to have the hasura methods to return the Errors/Error object used by graphql instead of a go error type?

**Comment by hgiasac** [comment]
Why don't you use `errors.As`?

```go
var gqlError graphql.Error
if errors.As(err, &gqlError) {
  log.Println(gqlErrors)
}

var gqlErrors graphql.Errors
if errors.As(err, &gqlErrors) {
  log.Println(gqlErrors)
}
```

**Comment by emilaleksanteri** [comment]
> Why don't you use `errors.As`?
> 
> ```go
> var gqlError graphql.Error
> if errors.As(err, &gqlError) {
>   log.Println(gqlErrors)
> }
> 
> var gqlErrors graphql.Errors
> if errors.As(err, &gqlErrors) {
>   log.Println(gqlErrors)
> }
> ```

ooh i didnt know this is possible (semi new to go), thank you so much, game changing!
