### ISSUE TITLE
How to mock graphql.Client?

### ISSUE THREAD

**Issue by koote** [hasura/go-graphql-client#138]
`graphql.Client` doesn't provide an interface, so how can I use gomock to create a mock of `graphql.Client` for testing? Thanks.

**Comment by hgiasac** [comment]
The graphql client is built upon a [Doer interface](https://github.com/hasura/go-graphql-client/blob/0fc7dc56e5214f496105c2fa3cd7f2f32633b548/graphql.go#L18). You can implement any mock client or use `httptest` client to intercept request and response data.

**Comment by koote** [comment]
@hgiasac That is too deep and too low level, means I need to manually create a graphql.Client based on a mock HTTP client, can we add an interface to graphql.Client so it can be mocked by using gomock?

**Comment by hgiasac** [comment]
I'm not sure about your needs. It's easy to write an interface for the graphql client 
For example, this is a [simple wrapper interface](https://github.com/hgiasac/graphql-utils/blob/main/client/interface.go) for mock test

**Comment by koote** [comment]
The interface is what I am looking for, but I cannot use it because currently `graphql.Client` is a struct not an interface, for example, this is my client code:
```
func Query(gqlClient *graphql.Client, some vars) error {
}
```
Because the function expect a object of `graphql.Client`, and it is a struct, I cannot pass in a mock implementation of the interface you shared.

In my understanding, the `graphql.Client` should be an interface (like you shared), not a struct:
```
type Client interface {
	Query(ctx context.Context, q interface{}, variables map[string]interface{}, options ...graphql.Option) error
	QueryRaw(ctx context.Context, q any, variables map[string]any, options ...graphql.Option) ([]byte, error)
	Mutate(ctx context.Context, m interface{}, variables map[string]interface{}, options ...graphql.Option) error
	MutateRaw(ctx context.Context, m interface{}, variables map[string]interface{}, options ...graphql.Option) ([]byte, error)
	Exec(ctx context.Context, query string, m any, variables map[string]any, options ...graphql.Option) error
	ExecRaw(ctx context.Context, query string, variables map[string]any, options ...graphql.Option) ([]byte, error)
}
```

So when test my function `Query`, I can pass any object in, as long as it implements the `Client` interface.

**Comment by hgiasac** [comment]
> The interface is what I am looking for, but I cannot use it because currently graphql.Client now is a struct not an interface, for example, this is my client code:
> Because the function expects a object of graphql.Client, and it is a struct, I cannot pass in a mock implementation of the interface you shared.

Can't you replace `graphql.Client` with the interface? Of course, you will need to modify your functions, but it's possible.

```go
type Client interface {
	Query(ctx context.Context, q interface{}, variables map[string]interface{}, options ...graphql.Option) error
        ...
}

func Query(gqlClient Client, some vars) error {
}
```

To clarify this library is the fork of https://github.com/shurcooL/graphql. The client was originally designed with a struct, and we haven't planned to change that design.

**Comment by koote** [comment]
That means I need to define an interface and wrap the `graphql.Client` within my project, I am thinking it is a bit not clean solution. But finally I managed to write my test in this way:
```
func Test_QueryAccounts(t *testing.T) {
        filter := getDefaultFilter()
	mux := http.NewServeMux()
	mux.HandleFunc("/graphql", func(writer http.ResponseWriter, request *http.Request) {
		body, err := io.ReadAll(request.Body)
		require.NoError(t, err)
		require.Equal(t, fmt.Sprintf(accountQueryBody, filter), string(body))

		queryResults, err := json.Marshal(testAccounts)
		require.NoError(t, err)

		_, err = io.WriteString(writer, fmt.Sprintf(accountQueryResponseWithoutError, queryResults))
		require.NoError(t, err)

		writer.Header().Set("Content-Type", "application/json")
	})
	testServer := httptest.NewServer(mux)
	defer testServer.Close()

	myClient, err := NewClient(&Config{Endpoint: testServer.URL + "/graphql"}, WithHTTPClient(http.DefaultClient))
	require.NoError(t, err)
	require.NotNil(t, myClient)

	accounts, err := myClient.QueryAccounts(context.Background(), filter)
	require.NoError(t, err)
	require.Equal(t, len(testAccounts), len(accounts))
}
```
