### ISSUE TITLE
How can I change the type name use variable?

### ISSUE THREAD

**Issue by xift810** [hasura/go-graphql-client#147]
![1111](https://github.com/user-attachments/assets/15105265-d130-49a1-947f-2249f9728f72)

we can use graphql tag to change type name 
But if we have different environment and different type name (product_xxxx), but graphql tag cannot using varaible and dynamic change . What can I do now? thx

**Comment by xift810** [comment]
Maybe "Exec/ExecRaw" can do this?

**Comment by hgiasac** [comment]
Yes, Go tags can not be modified in runtime. If you want to build dynamic query strings `Exec` is the only option.

**Comment by hgiasac** [comment]
close the issue. Please reopen if you have more questions.
