### ISSUE TITLE
 invalid memory address (*subscriptionsTransportWS)

### ISSUE THREAD

**Issue by Palaciodiego008** [hasura/go-graphql-client#157]
Hey what is new? I am using the package and setted the WithWebSocketOptions in this form:
![image](https://github.com/user-attachments/assets/dbf587cb-644a-422d-8ce5-8b169fa9015d)

But I have a issue when I ran the app using that.  Any suggest?

![image](https://github.com/user-attachments/assets/278dfb20-8893-4bd5-95ea-d5a135074a35)

![image](https://github.com/user-attachments/assets/7c9660c3-6736-4039-b076-203aa74100cf)

**Comment by hgiasac** [comment]
Hi @Palaciodiego008 

Can you share the entire logs and stack trace? That line only doesn't have enough context to debug.

**Comment by Palaciodiego008** [comment]
> Hi @Palaciodiego008
> 
> Can you share the entire logs and stack trace? That line only doesn't have enough context to debug.
This the rest of the debug. It not says very much.
![image](https://github.com/user-attachments/assets/63cb2056-08ee-4531-9b12-5e538340ca8b)

![image](https://github.com/user-attachments/assets/1b16fb05-c71f-4bcb-8ab9-287694930888)

and used the subscribe method in this way.

![image](https://github.com/user-attachments/assets/d85581ac-84af-441c-9d76-370a4e0d4002)

**Comment by hgiasac** [comment]
I see. The client failed to run due to other reasons. You can add the `WithLog` option to print debug logs

```go
 .WithLog(log.Println).
```

**Comment by Palaciodiego008** [comment]
> I see. The client failed to run due to other reasons. You can add the `WithLog` option to print debug logs
> 
> ```go
>  .WithLog(log.Println)
> ```
Enabling it, in the debug appears this, but really I don't know what mean.
![image](https://github.com/user-attachments/assets/3413644a-ae4d-4475-a22d-68364873775a)

I am using the subscription in this way, is ok? 

![image](https://github.com/user-attachments/assets/cf829389-aae5-417a-ac4d-c956542586d8)
![image](https://github.com/user-attachments/assets/f9803638-f5cc-45d1-89a6-5f2423b5b338)

(another doubt, Can I use query o subcription string and pass it like a parameter?)
![image](https://github.com/user-attachments/assets/c583777e-c54c-4dd1-86c3-efd2a7d4e71e)

**Comment by hgiasac** [comment]
In the `OnTransactionStatusUpdate` function you create the subscription client and then close it immediately. The subscription doesn't run. You should create only one singleton client and stop it before the process ends.

```go
defer client.Close()
```

If you prefer to use the raw query string you can use the `SubscribeRaw` method.

**Comment by Palaciodiego008** [comment]
> In the `OnTransactionStatusUpdate` function you create the subscription client and then close it immediately. The subscription doesn't run. You should create only one singleton client and stop it before the process ends.
> 
> ```go
> defer client.Close()
> ```
> 
> > (another doubt, Can I use query o subcription string and pass it like a parameter?)
> 
> If you prefer to use the raw query string you can use the `SubscribeRaw` method.

Got it, thanks!

![image](https://github.com/user-attachments/assets/0ed4f195-75d2-4c17-822b-68396ecd05a5)
I have checked and fixed more points (sorry I am new using this package), I had a problem, it looks more like the way I connect the websocket, what do you think?

**Comment by hgiasac** [comment]
I'm not sure. You should check the error information of the graphql server that the client is connecting to
