### ISSUE TITLE
Subscribe does not respect timeouts

### ISSUE THREAD

**Issue by andig** [hasura/go-graphql-client#159]
We have a server that does sometimes not answer to `Subscribe`. In that case our application stalls. Timeouts do not seem to handle this. 

I'm creating a subscription client with:

	WithRetryTimeout(10 * time.Second).
	WithTimeout(time.Second).

For such a client I would expect that `Subscribe` returns an error if subscription is not successful after `RetryTimeout`. However, the actual subscription never returns:

	_, err := t.client.Subscribe(&query, map[string]any{
		"homeId": graphql.ID(t.homeID),
	}, func(data []byte, err error) error {
		...
		return nil
	})
	if err != nil {
		...
	}

I would have expected that `Subscribe` returns with a timeout after a second since the underlying web socket connection seems intact. Instead, the log shows repeated retries until finally we hit the rate limit:

```
[pulse ] TRACE 2024/12/06 09:06:03 {"type":"connection_init","payload":{"token":"***"}} client
[pulse ] TRACE 2024/12/06 09:06:03 {"type":"connection_ack"} server
[pulse ] TRACE 2024/12/06 09:06:03 {"id":"c8565f2c-3d49-4b09-bc9b-fa7c0e213beb","type":"subscribe","payload":{"query":"subscription ($homeId:ID!){liveMeasurement(homeId: $homeId){power,powerProduction,lastMeterConsumption,lastMeterProduction,currentL1,currentL2,currentL3}}","variables":{"homeId":"***"}}} client
[pulse ] TRACE 2024/12/06 09:06:04 {"id":"c8565f2c-3d49-4b09-bc9b-fa7c0e213beb","type":"complete"} client
...
[pulse ] TRACE 2024/12/06 09:06:04 failed to WebSocket dial: expected handshake response status code 101 but got 429. retry in 1 second... client
```

Subscribe however _never_  returns an error.

Even with `WithRetryTimeout > 0` the `Subscribe` never returns. Without the `WithTimeout`, the `Subscribe` blocks:

```
[pulse ] TRACE 2024/12/06 09:12:46 POST https://api.tibber.com/v1-beta/gql
[pulse ] TRACE 2024/12/06 09:12:46 {"query":"{viewer{websocketSubscriptionUrl}}"}
--
{"data":{"viewer":{"websocketSubscriptionUrl":"wss://websocket-api.tibber.com/v1-beta/gql/subscriptions"}}}
[pulse ] TRACE 2024/12/06 09:12:46 {"type":"connection_init","payload":{"token":"***"}} client
[pulse ] TRACE 2024/12/06 09:12:46 {"type":"connection_ack"} server
[pulse ] TRACE 2024/12/06 09:12:46 {"id":"4c31a7fb-b003-411a-be8c-7eaa4520949a","type":"subscribe","payload":{"query":"subscription ($homeId:ID!){liveMeasurement(homeId: $homeId){power,powerProduction,lastMeterConsumption,lastMeterProduction,currentL1,currentL2,currentL3}}","variables":{"homeId":"***"}}} client

-> stalled
```

**Comment by hgiasac** [comment]
IIRC the timeout setting is for the Websocket connection only.  In your use case, the client could handshake the WebSocket connection successfully. The client then emits the subscription request and waits until the server responds. This process is asynchronous and doesn't have a timeout.

**Comment by andig** [comment]
Do you have a suggestion how to handle this server? I.e., if I start the subscription and a timeout in parallel- can I just re-subscribe when I come back later for another request? These would be two open subscription requests then?

**Comment by hgiasac** [comment]
> if I start the subscription and a timeout in parallel- can I just re-subscribe when I come back later for another request? These would be two open subscription requests then?

Yes. These would be two open subscription requests.
You can store the subscription ID and use the `client.Unsubscribe` method to stop the subscription.

**Comment by andig** [comment]
> You can store the subscription ID and use the client.Unsubscribe method to stop the current subscription before subscribing new one.

Tried this and found the resulting code really hard to read and cumbersome.

Looking at the flow once more and after doing some more testing I'm still not sure exactly what goes on:
- `WithRetryTimeout` cares about the physical connection- that is established
- `WithTimeout` is read/write timeout

What I see is that `Subscribe` never returns and repeats to subscribe after `WithTimeout`, even if `WithRetryTimeout` is non-zero. More specifically, it never returns after `WithRetryTimeout` (probably since the connection is alive).

All this is happening before the subscribe handler is ever invoked (which would happen asynchronously). That makes it- if I'm not totally mistaken- very hard to reason about Subscribe or handle subscription errors for this specific case.

I wish there was another timeout for this case- either specific to subscribe or potentially as a `WithMaxAttempts` that might limit the number of times a timeout is being retried.

Does this make any sense?

**Comment by hgiasac** [comment]
Just to clarify those timeout settings are used for the WebSocket connection only. 

The subscription follows Protocol specs ([subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md) and [graphql-ws](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md)) and the timeout is usually handled by the server side. I don't know how other clients handle this use case. The behavior is different in each protocol.

**Comment by andig** [comment]
Thank you, much appreciated.

**Comment by hgiasac** [comment]
FYI, [this PR](https://github.com/hasura/go-graphql-client/pull/162) adds a timeout for this use case. The subscription client will restart the WebSocket connection if the server doesn't reply to the acknowledge message after sending the `ConnectionInit` event. 

Please try it out and verify if you can reproduce the issue.
