### ISSUE TITLE
Installation instructions out-of-date / minimum go version is 1.16

### ISSUE THREAD

**Issue by schmr** [hasura/go-graphql-client#36]
Hi,

I just noticed that `go-graphql-client` release 0.7.1 uses `io.NopCloser`, which got introduced in go1.16 according to [the docs](https://pkg.go.dev/io#NopCloser). Contrary, in `README.md`, a minimum go version of 1.13 is stated.
Maybe bump the version number? I can create a pull request but it seems too minor of a change.

Thanks for your time!

**Comment by hgiasac** [comment]
Thanks for noticing. I will do that soon.
