### ISSUE TITLE
Remove canonical/vanity import path

### ISSUE THREAD

**Issue by RangelReale** [hasura/go-graphql-client#42]
Because of the comment after the package name in `doc.go`, the library expects to be imported as `github.com/shurcooL/graphql` and will not compile when imported as `github.com/hasura/go-graphql-client`, at least when using vendoring.

```
package graphql // import "github.com/shurcooL/graphql"
```

this is the error message I get

```
code in directory /workspace/src/entrypoint/vendor/github.com/hasura/go-graphql-client expects import "github.com/shurcooL/graphql"
```

I don't think this is the intention of this fork, so this probably should be removed.

Here is [documentation about Go vanity import](https://sagikazarmark.hu/blog/vanity-import-paths-in-go/).

**Comment by hgiasac** [comment]
closed by favor of https://github.com/hasura/go-graphql-client/pull/44. Can you update the version to v0.8.0 to confirm, thanks
