### ISSUE TITLE
ExecRaw method

### ISSUE THREAD

**Issue by therosco** [hasura/go-graphql-client#43]
Hey Hasura community,

Is there any reason there is no `ExecRaw()` method to get the raw response?

**Comment by hgiasac** [comment]
No, there isn't. We haven't implemented it yet

**Comment by therosco** [comment]
@hgiasac, any chance PRs are welcome? 😉

**Comment by hgiasac** [comment]
closed by favor of https://github.com/hasura/go-graphql-client/pull/44. Let's update the version to v0.8.0

**Note**: there is a breaking change in `*Raw` response type. If you use them or subscriptions before, please update the syntax as well.
