### ISSUE TITLE
nhooyr.io/websocket module uses a vulnerable version of github.com/gin-gonic/gin

### ISSUE THREAD

**Issue by psybits** [hasura/go-graphql-client#50]
The nhooyr.io/websocket project seems abandoned for now. A temporary fix is to replace v1.8.7 with v1.8.8-0.20210726233605-fd3348372773 for websocket in go.mod.

The new version comes from this commit: https://github.com/nhooyr/websocket/commit/fd33483727735edb472af5f568562f66fd9ab374

**Comment by hgiasac** [comment]
AFAIK the websocket library only uses `gin` for testing. The vulnerable version doesn't affect the library. It isn't necessary to update.

**Comment by psybits** [comment]
Ah sorry I should've looked into it. Here's for anyone who stumbles upon this and is worried: https://github.com/nhooyr/websocket/search?q=gin
At the time of writing this is true, but check the link in case something has changed later and the version is still not bumped!
