### ISSUE TITLE
Run() semantics- how to check for error?

### ISSUE THREAD

**Issue by andig** [hasura/go-graphql-client#57]
I'm trying to figure out if the client actually successfully started:

	client := graphql.NewSubscriptionClient(tibber.SubscriptionURI).
		WithConnectionParams(map[string]any{
			"token": cc.Token,
		}).
		WithLog(t.log.TRACE.Println)

	// run the client
	errC := make(chan error)

	go func() {
		errC <- client.Run()
	}()

	err := <-errC

Unfortunately this will deadlock sind `Run()` will only return _if_ it errors. It would be nice if we had a means of determining if the client started successfully, too.

**Comment by hgiasac** [comment]
@andig Have you tried listening to `OnConnected` and `OnError` events?

https://github.com/hasura/go-graphql-client#events

**Comment by andig** [comment]
Excellent, thank you!
