### ISSUE TITLE
How are subscriptions handled on reconnect?

### ISSUE THREAD

**Issue by andig** [hasura/go-graphql-client#64]
We have the problem that subscriptions are not re-established when the connection is reconnected. Looking at the code it seems if that is unexpected? 
Looking into this in more detail I'm wondering if we're just seeing the retry timeout expire. Is it possible to retry without limit?

**Comment by utsavanand2** [comment]
@andig I'm having the same issue with the library. Have you been able to figure out a workaround?

**Comment by hgiasac** [comment]
This PR https://github.com/hasura/go-graphql-client/pull/67 improves the reconnection behavior. Please try and give feedback, thanks

**Comment by andig** [comment]
Thank you, we'll verify this.

**Comment by andig** [comment]
Thank you, confirmed working!
