### ISSUE TITLE
How to struct grapghql code

### ISSUE THREAD

**Issue by sridharchary** [hasura/go-graphql-client#70]
this is my grapghql structure, but I would like to know in golang
```
	query{
	  questions{
	    data{
	      	attributes{
	          title
	          description
	          question_id
	        }
	    }

  }
}
```
I wrote code for client to get data from graphql, Like this but it's not working.  

```
var que struct {
		Questions struct {
			Data struct {
				Attributes []struct {
					Question_id graphql.String
					Title       graphql.String
					Description graphql.String
				}
			}
		}
	}
```
showing this Error
`slice doesn't exist in any of 1 places to unmarshalError comes in
exit status 1`

in browser showing data Like this
`{
  "data": {
    "questions": {
      "data": [
        {
          "attributes": {
            "title": "I got issue with keyword error",
            "description": "I have issue with keyerror in python",
            "question_id": null
          }
        },
        {
          "attributes": {
            "title": "memory error",
            "description": "while runnig code i got this issue",
            "question_id": null
          }
        }
      ]
    }
  }
}`

**Comment by hgiasac** [comment]
Hi

You have mistaken the type of `data` and `attributes`. `data` should be an array and `attributes` should be an object

```go
var que struct {
		Questions struct {
			Data []struct {
				Attributes struct {
					Question_id graphql.String
					Title       graphql.String
					Description graphql.String
				}
			}
		}
	}
```

**Comment by sridharchary** [comment]
thanks @hgiasac. it's worked for me
