### ISSUE TITLE
mutation in golang client not working 

### ISSUE THREAD

**Issue by sridharchary** [hasura/go-graphql-client#71]
Can you Please help to find solution, For Mutation 
`var m struct {
		CreateQuestion struct {
			Data struct {
				Id         graphql.ID
				Attributes struct {
					Question_id graphql.String
					Title       graphql.String
					Description graphql.String
				}
			}
		} `graphql:"createQuestion(data: $data)"`
	}
`
Defined Variables Like this
`
type user_insert_input map[string]interface{}
variables := map[string]interface{}{
		"data": []user_insert_input{
			"question_id": "2451",
			"title":       "python struct",
			"description": "brief description of python syntax error",
		},
	}
err := cli.Mutate(context.Background(), &m, variables)
`
Error was Look like
`cannot convert "question_id" (untyped string constant) to int
./client.go:69:19: cannot use "2451" (untyped string constant) as user_insert_input value in array or slice literal`

**Comment by hgiasac** [comment]
The error is self-explained. The type of `quesion_id` is `int`, but you define it as a `string`

**Comment by hgiasac** [comment]
Closed due to inactivity
