### ISSUE TITLE
security issue with github.com/gin-gonic/gin

### ISSUE THREAD

**Issue by rafaelvanoni** [hasura/go-graphql-client#73]
github's dependabot flagged versions < 1.7.0 of `github.com/gin-gonic/gin` with the following issue
```
This affects all versions of package github.com/gin-gonic/gin under 1.7.0. When gin is exposed directly to the internet, a client's IP can be spoofed by setting the X-Forwarded-For header.
```

**Comment by rafaelvanoni** [comment]
Looks like this is imported as a dependency of `nhooyr.io/websocket`, is it possible to upgrade that package?

**Comment by hgiasac** [comment]
There hasn't been any new update from `nhooyr.io/websocket`. Therefore we can't update as well unless we fork it to another repository. Reference: https://github.com/nhooyr/websocket/issues?q=gin
AFAIK the library uses `github.com/gin-gonic/gin` for unit tests only. The library is still safe to be used.

**Comment by rafaelvanoni** [comment]
I was able to work around this with
```
replace github.com/gin-gonic/gin v1.6.3 => github.com/gin-gonic/gin v1.7.7
```

**Comment by hgiasac** [comment]
closed by favor of https://github.com/hasura/go-graphql-client/commit/10471cf9d8df859e36584a8821e5ffc3d91c76b8
