### ISSUE TITLE
Smallint type problem

### ISSUE THREAD

**Issue by dogukanoksuz** [hasura/go-graphql-client#90]
Hello,

Thanks for great work, i appreciate it. Library works great with Hasura but i am encountered a bug.

When mutating, i must send smallint as type but when i create smallint as type on Golang it still returns Int!

This typecasting works with strings without problems but on int values i encounter this error;

```
Message: variable 'user_defined' is declared as 'Int', but used where 'smallint' is expected, Locations: [], Extensions: map[code:validation-failed path:$.selectionSet.....]
```

<img width="627" alt="image" src="https://user-images.githubusercontent.com/32539161/234042351-48e8473d-af8e-4f2d-8ed5-af811c7a65af.png">

Thanks.

**Comment by hgiasac** [comment]
I guess the type reflection can't infer private types from other packages. You can try to define the inline type in the same package, for instance:

```go
type smallint int
err := gql.Connection().Mutate(context.Background(), &q, map[string]interface{}{
  "user_defined": smallint(1)
})
``` 

Another approach is [GraphQLType interface](https://github.com/hasura/go-graphql-client#specify-graphql-type-name)  if you like to reuse that type for multiple packages.

```go
type SmallInt int

func (i SmallInt) GetGraphQLType() string { 
  return "smallint" 
}
```

**Comment by dogukanoksuz** [comment]
Looks like second approach works.

As i tested we can reflect private types from other packages if it's based on string.

I think this lines causes the bug;

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/32539161/234199009-61eed911-e1fa-4bde-83d5-dcbbef1f09c5.png">
